### ISSUE TITLE
Runtime error when >GO TO GAME SHELL

### ISSUE THREAD

**Issue by juhana** [andrewschultz/the-problems-compound#80]
> A loud, hearty voice from the shell. "Howdy! I'm Guy Sweet! You look like a fella with a games mind! Why not come over to the Game Shell and have a TALK?"
> 
> >go to game shell
> 
> **\* Run-time problem P10: Since the Game Shell is not allowed the property "map region", it is against the rules to try to use it.
> 
> that isn't around right now.
> 
> >

**Comment by andrewschultz** [comment]
Oops.

```
let mrlg be map region of noun;
```

should be

```
let mrlg be map region of location of noun;
```

Fixed, but untested.
