### ISSUE TITLE
Missing line break after Howdy Boy interaction

### ISSUE THREAD

**Issue by juhana** [andrewschultz/the-problems-compound#82]
> **Pressure Pier**
> Water south, passage north. You smell food to the west, and the land sinks a bit to the east. Ahead north, things open up further behind the Saver Screen.
> 
> The Howdy Boy stands here, looking disinterested now he's greeted you.
> 
> "Oh, hey! Still here? I'm moving ahead in life!" you say to the Howdy Boy, who runs off in embarrassment.
> >

Missing a line break before the prompt.

**Comment by juhana** [comment]
Also right after that with the jerks:

> "Oh! Hey! You all talking about something interesting? I won't disturb you. Which way is the BM?" They look shocked you...USED HIS INITIALS. They point north. "I KNOW," you boom. They scatter.
> >

**Comment by juhana** [comment]
Also right after that:

> You give a pre-emptive "Oh, I KNOW," before Turk and Dutch can say any more. "But you're doing a pretty good job. I mean, almost as good as I could if I weren't destined for better things."
> >

**Comment by andrewschultz** [comment]
Ah--got these. I had the proper line break in 1 ending but not the other 3. This got swept up in another transcript I had.

Also I cleared up that the endings were existential failures and the player may want to try again.
